# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2
  maven: circleci/maven@1.2.0
jobs:
    build:
        docker:
            - image: circleci/node:12
        steps:
            - run: maven/test


